min_version = "2026.7.5"

[settings]
lockfile = true

[tools]
go = "1.26.6"
"aqua:goreleaser/goreleaser" = "2.17.1"
"go:github.com/google/go-licenses/v2" = "v2.0.1"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.7.0"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.5.1",
]
