name: Compatibility

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-go.yml@1d71352b525cf485394527db3e6a4c4c707b4377 # v8.7.0
    with:
      go-versions: '["1.25","1.26"]'
