name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-go.yml@cdc42cf2f91fd796de35bdc27aaaa1057695afcc # v6.1.0
    with:
      go-versions: '["1.25","1.26"]'
