name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-go.yml@7e1e1b73633f829ea0ac1ca934aa4d085561d61a # v7.1.0
    with:
      go-versions: '["1.25","1.26"]'
