name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-homebrew-tap.yml@3a106f414b2ee346211a9c9050a27e2f26336796 # v7.0.0
    permissions:
      contents: write  # to draft and publish the GitHub Release and upload binary archives
    secrets:
      homebrew_tap_app_client_id: ${{ secrets.HOMEBREW_TAP_APP_CLIENT_ID }}
      homebrew_tap_app_private_key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
