name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-homebrew-tap.yml@d21b0a8606441bf9ace76ad014a80a9165de3a36 # v6.2.0
    permissions:
      contents: write  # to draft and publish the GitHub Release and upload binary archives
    secrets:
      homebrew_tap_app_client_id: ${{ secrets.HOMEBREW_TAP_APP_CLIENT_ID }}
      homebrew_tap_app_private_key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
