name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    uses: iwamot/workflows/.github/workflows/release-homebrew-tap.yml@7e1e1b73633f829ea0ac1ca934aa4d085561d61a # v7.1.0
    permissions:
      contents: write  # to draft and publish the GitHub Release and upload binary archives
    secrets:
      homebrew_tap_app_client_id: ${{ secrets.HOMEBREW_TAP_APP_CLIENT_ID }}
      homebrew_tap_app_private_key: ${{ secrets.HOMEBREW_TAP_APP_PRIVATE_KEY }}
